#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Gabriel's Menswear GA4 + Google Ads measurement setup.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SA="ga4-admin@gabriels-menswear-ga.iam.gserviceaccount.com"
SA_PROJECT="gabriels-menswear-ga"
# The human identity that impersonates the service account. No key file is ever
# written to disk: gcloud mints a short-lived token through your own login.
IMPERSONATOR="${GA_IMPERSONATOR:-$(gcloud config get-value account 2>/dev/null)}"
GA_SCOPES="https://www.googleapis.com/auth/analytics.edit,https://www.googleapis.com/auth/analytics.readonly"
API="https://analyticsadmin.googleapis.com/v1beta"
MEASUREMENT_ID="G-GBHF2MRV3Z"
OLD_MEASUREMENT_ID="G-7JVW4GWN9G"
EXPECTED_ADS_ID="939961826"
SITE_URL="https://gabrielsmenswear.com/"
KEY_EVENTS=(call_click directions_click reviews_click)

PY=python
command -v python >/dev/null 2>&1 || PY=python3

# ga_token mints a short-lived analytics-scoped token by impersonating the
# service account. Deliberately no x-goog-user-project header below: a service
# account bills quota to its own project, and sending one makes the API 403.
ga_token() {
  gcloud auth print-access-token --account="$IMPERSONATOR" \
    --impersonate-service-account="$SA" --scopes="$GA_SCOPES" 2>/dev/null
}
# ga_get PATH and ga_post PATH BODY call the GA4 Admin API.
ga_get()  { curl -sS -H "Authorization: Bearer $(ga_token)" "$API/$1"; }
ga_post() { curl -sS -X POST -H "Authorization: Bearer $(ga_token)" \
              -H 'Content-Type: application/json' -d "$2" "$API/$1"; }
# jqp EXPR reads JSON on stdin as d and prints EXPR. Python, so no jq dependency.
jqp() { "$PY" -c "import json,sys
d=json.load(sys.stdin)
$1" 2>/dev/null; }
# summaries_accounts / summaries_properties parse an accountSummaries payload.
summaries_accounts()   { jqp 'print(",".join(a["account"] for a in d.get("accountSummaries",[])))'; }
summaries_properties() { jqp 'print("\n".join(p["property"]+"\t"+p.get("displayName","") for a in d.get("accountSummaries",[]) for p in a.get("propertySummaries",[])))'; }
api_error()            { jqp 'print(d["error"]["message"])'; }

banner "Gabriel's Menswear: GA4 + Ads measurement"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: service-account API access"
say "Everything here runs as a service account, so no browser login is needed"
say "except for the one grant in the next stage."
note "service account: $SA"
if ! command -v gcloud >/dev/null 2>&1; then
  warn "gcloud is not on PATH. Install the Google Cloud SDK, then re-run."
  exit 1
fi
printf '  checking token and API... '
if [[ -z "$(ga_token)" ]]; then
  printf '\n'
  warn "could not mint a token by impersonating $SA as $IMPERSONATOR."
  note "That identity needs roles/iam.serviceAccountTokenCreator on the account:"
  note "  gcloud iam service-accounts add-iam-policy-binding $SA \\"
  note "    --project=$SA_PROJECT --member=user:$IMPERSONATOR \\"
  note "    --role=roles/iam.serviceAccountTokenCreator"
  note "A fresh grant can take a few minutes to propagate; re-run if you just made it."
  exit 1
fi
PREFLIGHT=$(ga_get "accountSummaries")
if grep -q '"error"' <<<"$PREFLIGHT"; then
  printf '\n'
  warn "the Admin API rejected the call:"
  note "$(api_error <<<"$PREFLIGHT")"
  note "If it says the API is disabled, run:"
  note "  gcloud services enable analyticsadmin.googleapis.com --project=$SA_PROJECT"
  exit 1
fi
printf '%s+%s ok\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Grant the service account access to Analytics"
say "This is the only step a human has to do. The API cannot grant itself access."
if [[ -n "$(summaries_accounts <<<"$PREFLIGHT")" ]]; then
  printf '  %s+%s access already granted, skipping\n' "$GREEN" "$RESET"
else
  open_url "https://analytics.google.com/analytics/web/#/a/accesscontrol"
  step "Admin -> Account access management (account level, NOT property level)."
  step "Click + in the top right, then Add users."
  step "Paste this address as the email:"
  printf '\n      %s%s%s\n\n' "$BOLD" "$SA" "$RESET"
  step "Untick 'Notify new users by email' - it is a service account, no inbox."
  step "Set Standard roles to Editor, then click Add."
  note "Account level, not property level, so this script can see every property"
  note "and tell you which one is actually live."
  warn "This grants standing Editor access until you remove it in the same screen."
  for attempt in 1 2 3 4 5 6 7 8 9 10; do
    pause "Done? Press Enter and I will verify"
    PREFLIGHT=$(ga_get "accountSummaries")
    if [[ -n "$(summaries_accounts <<<"$PREFLIGHT")" ]]; then
      printf '  %s+%s access confirmed\n' "$GREEN" "$RESET"
      break
    fi
    warn "still seeing zero accounts (attempt $attempt/10). Grants can take a minute."
  done
fi
if [[ -z "$(summaries_accounts <<<"$PREFLIGHT")" ]]; then
  warn "no Analytics accounts visible. Re-run once the grant has propagated."
  exit 1
fi
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Identify the live property"
say "The site reports to $MEASUREMENT_ID. The archived mainstreetmenswear.com"
say "site used $OLD_MEASUREMENT_ID. Finding which property owns the live ID."
PROPERTIES=$(summaries_properties <<<"$PREFLIGHT")
PROPERTY=""
PROPERTY_NAME=""
while IFS=$'\t' read -r prop name; do
  [[ -z "$prop" ]] && continue
  printf '  scanning %s (%s)... ' "$name" "$prop"
  STREAMS=$(ga_get "$prop/dataStreams")
  ids=$(jqp 'print(" ".join(s.get("webStreamData",{}).get("measurementId","") for s in d.get("dataStreams",[])))' <<<"$STREAMS")
  printf '%s\n' "${ids:-no web streams}"
  if [[ " $ids " == *" $MEASUREMENT_ID "* ]]; then
    PROPERTY="$prop"
    PROPERTY_NAME="$name"
  fi
  if [[ " $ids " == *" $OLD_MEASUREMENT_ID "* ]]; then
    note "  ^ this is the archived mainstreetmenswear.com property"
  fi
done <<<"$PROPERTIES"
if [[ -z "$PROPERTY" ]]; then
  warn "no property in this account carries $MEASUREMENT_ID."
  say "That means the live site reports to a property you cannot see, or the"
  say "measurement ID on the site is stale. Pick one manually or stop here."
  printf '%s\n' "$PROPERTIES" | sed 's/^/    /'
  ask GA4_PROPERTY_ID "Paste a property path (properties/123456789) or Enter to abort:"
  PROPERTY="$GA4_PROPERTY_ID"
  if [[ -z "$PROPERTY" ]]; then
    warn "aborting; nothing was changed."
    exit 1
  fi
fi
printf '  %s+%s live property: %s (%s)\n' "$GREEN" "$RESET" "$PROPERTY_NAME" "$PROPERTY"
write_env GA4_PROPERTY_ID "${PROPERTY#properties/}"
write_env GA4_MEASUREMENT_ID "$MEASUREMENT_ID"
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Register the three key events"
say "Until these exist, GA4 collects the events but does not count them as"
say "conversions, and Google Ads cannot import them."
EXISTING=$(ga_get "$PROPERTY/keyEvents" | jqp 'print(" ".join(e.get("eventName","") for e in d.get("keyEvents",[])))')
for ev in "${KEY_EVENTS[@]}"; do
  if [[ " $EXISTING " == *" $ev "* ]]; then
    printf '  %s+%s %s already registered\n' "$GREEN" "$RESET" "$ev"
    continue
  fi
  printf '  creating %s... ' "$ev"
  RESP=$(ga_post "$PROPERTY/keyEvents" "{\"eventName\":\"$ev\",\"countingMethod\":\"ONCE_PER_EVENT\"}")
  if grep -q '"error"' <<<"$RESP"; then
    printf '%sfailed%s\n' "$RED" "$RESET"
    note "$(api_error <<<"$RESP")"
    SKIPPED+=("key event $ev - create by hand: Admin -> Key events -> New key event")
  else
    printf '%s+%s ok\n' "$GREEN" "$RESET"
  fi
done
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify against live traffic"
say "Key events only count from now on, so let's prove the site still fires them."
open_url "https://analytics.google.com/analytics/web/#/${PROPERTY#properties/}/realtime/overview"
open_url "$SITE_URL"
step "In the site tab, click a phone number, a Get directions link, and a"
step "Google review link. Middle-click each, or come straight back after."
step "In the Realtime tab, watch 'Event count by Event name'."
note "Expect call_click, directions_click and reviews_click as three distinct names."
note "If review clicks land as directions_click, the deployed site predates f7a4eb9."
if confirm "Did all three appear as separate events?"; then
  printf '  %s+%s tracking confirmed end to end\n' "$GREEN" "$RESET"
else
  SKIPPED+=("verify events in Realtime - run: node lab/events.mjs $SITE_URL")
  warn "noted. The offline harness will tell you which one is wrong."
fi
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Audit the Google Ads link (read-only, no spend)"
say "Ads are not starting yet. This stage only records what already exists."
ADSLINKS=$(ga_get "$PROPERTY/googleAdsLinks")
FOUND=$(jqp 'print(" ".join(l.get("customerId","") for l in d.get("googleAdsLinks",[])))' <<<"$ADSLINKS")
ADS_ID=""
if [[ -n "$FOUND" ]]; then
  printf '  %s+%s linked Ads customer ID(s): %s\n' "$GREEN" "$RESET" "$FOUND"
  ADS_ID=$(awk '{print $1}' <<<"$FOUND")
else
  warn "no Google Ads link on this property."
  note "The old site's GTM carried conversion ID AW-$EXPECTED_ADS_ID. It is"
  note "unverified whether that account is yours or the previous operator's."
  open_url "https://analytics.google.com/analytics/web/#/${PROPERTY#properties/}/admin/googleads"
  step "Admin -> Product links -> Google Ads links. Read the customer ID if one is there."
  ask GOOGLE_ADS_CUSTOMER_ID "Google Ads customer ID (digits only, or Enter to skip):"
  ADS_ID="$GOOGLE_ADS_CUSTOMER_ID"
fi
if [[ -n "$ADS_ID" ]]; then
  write_env GOOGLE_ADS_CUSTOMER_ID "$ADS_ID"
  if [[ "${ADS_ID//-/}" == "$EXPECTED_ADS_ID" ]]; then
    printf '  %s+%s matches AW-%s from the old GTM container\n' "$GREEN" "$RESET" "$EXPECTED_ADS_ID"
  else
    warn "does NOT match AW-$EXPECTED_ADS_ID from the old container."
    note "So that conversion ID likely belongs to whoever ran mainstreetmenswear.com."
    note "Do not wire anything to it without confirming ownership."
  fi
else
  SKIPPED+=("confirm the Google Ads customer ID before any remarketing tag work")
fi

finish
